apiVersion: v1
kind: Pod
metadata:
  name: event-logger-backend
spec:
  restartPolicy: on-failure
  containers:
    - name: event-logger-backend
      image: localhost/event-logger-backend:latest
      ports:
        - containerPort: 8000
          hostIp: 127.0.0.1
          hostPort: 8000
      env:
        - name: port
          value: 8000
        - name: xtdburl
          value: http://xtdb:3000
    - name: xtdb
      image: ghcr.io/xtdb/xtdb
      ports:
        - containerPort: 3000
          hostIp: 127.0.0.1
          hostPort: 3000
        - containerPort: 5432
          hostIp: 127.0.0.1
          hostPort: 5432
      volumeMounts:
        - mountPath: /var/lib/xtdb
          name: xtdb-data
  volumes:
    - name: xtdb-data
      persistentVolumeClaim:
        claimName: xtdb-data
